{% set name = "reno-sd" %}
{% set python_min = "3.11" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reno_sd-{{ version }}.tar.gz
  sha256: ecff6bae2887ac8eef846a20648d57143cd17d76696186f4452de4f1ad10d293

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.14
    - numpy
    - pandas
    - xarray
    - panel
    - pymc
    - matplotlib-base
    - selenium
    - ipyvuetify
    - python-graphviz

test:
  imports:
    - reno
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ORNL/reno
  summary: System dynamics modeling with bayesian inference
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ornl.github.io/reno/stable/index.html

extra:
  recipe-maintainers:
    - WarmCyan
